### ISSUE TITLE
BUG: Migrations update from 1.4 to 2.0 or 2.1

### ISSUE THREAD

**Issue by michtio** [wbrowar/craft-guide#22]
if I try to upgrade from guide 1.4.0 to guide 2.0.1 or the latest 2.1.2 or anything in between there is always a migration error showing up.

```
Exception: Undefined offset: 13 (/Users/michtio/dev/researchschoolsnetwork/craft/vendor/wbrowar/guide/src/migrations/m190703_015029_convert_user_guides.php:200)
#0 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/wbrowar/guide/src/migrations/m190703_015029_convert_user_guides.php(200): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/Users/michtio/...', 200, Array)
#1 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/wbrowar/guide/src/migrations/m190703_015029_convert_user_guides.php(40): wbrowar\guide\migrations\m190703_015029_convert_user_guides->convertUserGuideToGuide()
#2 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/craftcms/cms/src/db/Migration.php(56): wbrowar\guide\migrations\m190703_015029_convert_user_guides->safeUp()
#3 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/craftcms/cms/src/db/MigrationManager.php(239): craft\db\Migration->up(true)
#4 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/craftcms/cms/src/db/MigrationManager.php(159): craft\db\MigrationManager->migrateUp(Object(wbrowar\guide\migrations\m190703_015029_convert_user_guides))
#5 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#6 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/craftcms/cms/src/console/controllers/MigrateController.php(265): craft\services\Updates->runMigrations(Array)
#7 [internal function]: craft\console\controllers\MigrateController->actionAll()
#8 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#11 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#12 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#13 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#14 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#15 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#16 /Users/michtio/dev/researchschoolsnetwork/craft/craft(22): yii\base\Application->run()
#17 {main}
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Guide.'

in /Users/michtio/dev/researchschoolsnetwork/craft/vendor/craftcms/cms/src/services/Updates.php:233

Stack trace:
#0 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/craftcms/cms/src/console/controllers/MigrateController.php(265): craft\services\Updates->runMigrations(Array)
#1 [internal function]: craft\console\controllers\MigrateController->actionAll()
#2 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('all', Array)
#5 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#6 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#7 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('migrate/all', Array)
#8 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#9 /Users/michtio/dev/researchschoolsnetwork/craft/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#10 /Users/michtio/dev/researchschoolsnetwork/craft/craft(22): yii\base\Application->run()
#11 {main}
```

This makes it quite impossible to upgrade the old guide to the new one.

**Comment by wbrowar** [comment]
Thanks, @michtio! I'll take a look after I get back from DotAll. I asked a co-worker and he was able to re-create this on his end. He said to run `./craft migrate/all` via command line to get the migration to work for now. Hope that works.

**Comment by michtio** [comment]
Thank you @wbrowar 

I tried manually running the migration and that did indeed seem to be running fine. Just as additional information on why I didn't try to run it another time manually is because in the `composer.json` file on the post-update hook 
```"post-update-cmd": [
      "./craft migrate/all"
    ]```
 is being executed. Which should just be the same as the CLI command.

So that is some additional information for you to try, I have not tried `@php craft migrate/all`. 

And enjoy DotAll! Too bad I couldn't make it.
